### ISSUE TITLE
Authorization header

### ISSUE THREAD

**Issue by reminder2k1** [silvioprog/brookframework#133] opened 2017-03-25 09:38 UTC
Hi guys,

I tried to get authorization variable value on headers on CGI App, but it not shown. Then i tried with the same method use FCHttpApp it normal. Something bug on CGI App?

Thx...

**Comment by silvioprog** [comment] 2017-03-25 17:26
Hello @reminder2k1 ,

Brook 3 just iterate the FPC properties. Could you show how you are tying?

**Comment by reminder2k1** [comment] 2017-03-26 06:27
<img width="1920" alt="screen shot 2017-03-26 at 1 25 24 pm" src="https://cloud.githubusercontent.com/assets/967982/24329161/b9cf5702-1227-11e7-9a7c-84ee75db45af.png">

i created a action, with simple debugging for cgi (save to log), and execute it use postman.
what i miss ?

**Comment by silvioprog** [comment] 2017-03-26 14:46
Hello @reminder2k1 , I can't reproduce the problem with a screenshot. Notice the `Authorization` header is a server-side variable, so you need to check if your server (Apache, nginx, IIS etc.) is really passing the variable to the CGI instance. The small CGI application below prints all environment variables, so you can use it checking if the authorization variable is present:

```pascal
program project1;

{$mode delphi}

uses sysutils;

var
  i: integer;
  s: string;
begin
  s := '';
  for i := 1 to GetEnvironmentVariableCount do
    s := s + GetEnvironmentString(i) + sLineBreak;
  WriteLn('Content-Type: text/plain');
  WriteLn;
  WriteLn(s);
end.
```

**Comment by derit** [comment] 2017-03-28 13:29
hi silvio 
the problem, from client send the header to brook cgi app
but cgi app can't parsing the header 
TheRequest.Authorization  // doesn't work 
 TheRequest.Accept // yes  work

**Comment by silvioprog** [comment] 2017-03-28 13:55
Are you using an external HTTP server or is that problem related to embedded one?

**Comment by derit** [comment] 2017-03-28 14:22
i used cgi simple application 
and client use postman for send header to h

![screenshot_169](https://cloud.githubusercontent.com/assets/5389364/24410192/a63ba110-13fc-11e7-8673-3c3c07d8ca8c.png)

**Comment by silvioprog** [comment] 2017-03-28 14:42
Hello @derit . Re-asking: which server are you using? Did you test the example I've passed to check if your server is passing the environment variables to the Pascal side? Please see my question above and try the steps I've said. I can't reproduce this problem on Ubuntu 16.04 with Apache 2.4.18.

**Comment by reminder2k1** [comment] 2017-03-28 15:31
I using apache 2.2.4

**Comment by silvioprog** [comment] 2017-03-28 15:38
On Linux? If so, which one?1

**Comment by derit** [comment] 2017-03-28 21:30
environment
server apache 2.2.4 on windows 10 64bit

**Comment by reminder2k1** [comment] 2017-03-29 00:39
no, i use windows 10

**Comment by derit** [comment] 2017-04-02 06:08
<solved>
i've found the problem in apache authorization
add this script in htaccess 
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

**Comment by silvioprog** [comment] 2018-11-02 22:59
Closing due to already solved problem. Thanks for reporting!

**Closed by silvioprog** 2018-11-02 22:59 UTC
