### ISSUE TITLE
Pattern / is never matched

### ISSUE THREAD

**Issue by leledumbo** [silvioprog/brookframework#129] opened 2016-09-10 19:51 UTC
I have the following Register call:

``` pascal
THome.Register('/',rmGet);
```

However, that / pattern is never matched. It causes infinite redirection (307 over and over again). Debugging TBrookRouter.MatchPattern, it seems to be caused by:

``` pascal
if (APattern = US) and (APathInfo = ES) then
begin
  ARedirect := True;
  Exit(True);
end;
```

which in turn will cause:

``` pascal
if VRedirect and Canonicalize(ARequest, AResponse) then
  Exit;
```

in which Canonicalize will send the 307 response with the same empty pathinfo, hence the infinite redirection.

This problem also applies to empty string pattern, setting default parameter to true doesn't seem to help either (only moves the block where to get action class, but the result is the same).

In the mean time, I register a `BeforeRoute` callback to redirect empty or slash path info to /home, but I expect they will be properly handled later. I think I understand already what you have in mind when coding the `Route` method, just unexpectedly not working. A little refactor should fix it, it's just a matter of who will solve it first, you or me :D

**Comment by silvioprog** [comment] 2016-09-12 21:48
Hm... I need to test it, could you share the test (tools, steps ...) used in the client side? Anyway feel free to solve it. :-)

**Comment by leledumbo** [comment] 2016-09-12 22:24
not so difficult:

```pascal
{$mode objfpc}{$H+}

uses
  BrookAction, BrookUtils, BrookFCLHTTPAppBroker, BrookApplication;

type
  THelloWorldAction = class(TBrookAction)
    procedure Get; override;
  end;

procedure THelloWorldAction.Get;
begin
  Write('Hello, World!');
end;

begin
  THelloWorldAction.Register('/',rmGet);
  BrookSettings.Port := 8080;
  Application.Run;
end.
```
tested with curl:
```text
$ curl -vvv localhost:8080
* Rebuilt URL to: localhost:8080/
*   Trying ::1...
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.50.1
> Accept: */*
> 
< HTTP/1.1 307 Temporary Redirect
< X-Powered-By: Brook framework and FCL-Web.
< Status: 307 Temporary Redirect
< Content-Type: text/html; charset=utf-8
< Location: /
* no chunk, no close, no size. Assume close to signal end
< 
* Closing connection 0
$ curl -vvv localhost:8080/
*   Trying ::1...
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.50.1
> Accept: */*
> 
< HTTP/1.1 307 Temporary Redirect
< X-Powered-By: Brook framework and FCL-Web.
< Status: 307 Temporary Redirect
< Content-Type: text/html; charset=utf-8
< Location: /
* no chunk, no close, no size. Assume close to signal end
< 
* Closing connection 0
```
pass -L to curl and infinite 307 will reveal itself. You can try registering empty string pattern as well, same result.

**Comment by MFernstrom** [comment] 2017-06-26 17:52
I'm seeing the same behaviour.

Not much needed to test it, just register "/" and try to visit in the browser.

**Comment by MFernstrom** [comment] 2017-09-14 18:32
@leledumbo would you mind sharing how you set up your beforeroute handler?  The matching is still a problem.

**Comment by leledumbo** [comment] 2017-09-14 18:44
@MFernstrom:
```pascal
unit AutoDisconnectRouter;

{$mode objfpc}{$H+}

interface

implementation

uses
  Classes, BrookAction, BrookUtils, BrookHttpDefs, BrookConsts, BrookRouter;

type

  { TAutoDisconnectRouter }

  TAutoDisconnectRouter = class(TBrookRouter)
  public
    constructor Create(AOwner: TComponent); override;
    procedure RedirectEmptyOrSlash(ASender: TObject; ARequest: TBrookRequest;
      AResponse: TBrookResponse; var AHandled: Boolean);
  end;

{ TAutoDisconnectRouter }

constructor TAutoDisconnectRouter.Create(AOwner: TComponent);
begin
  inherited Create(AOwner);
  BeforeRoute := @RedirectEmptyOrSlash;
end;

procedure TAutoDisconnectRouter.RedirectEmptyOrSlash(ASender: TObject;
  ARequest: TBrookRequest; AResponse: TBrookResponse; var AHandled: Boolean);
begin
  if ARequest.PathInfo = ES then begin
    AResponse.SendRedirect('/home');
    AHandled := true;
  end;
end;

initialization
  BrookRouter._BrookRouterServiceClass := TAutoDisconnectRouter;

end.
```
Ignore the name, this class actually does more than just `BeforeRoute` registration.

**Comment by MFernstrom** [comment] 2017-09-14 21:34
Thanks @leledumbo I'll give this a shot.

I got it working by using an nginx rule but would much rather solve this in the program.

**Comment by silvioprog** [comment] 2018-11-02 22:56
Hi dudes. Closing due to old issue. Please feel free to reissue if the problem persists! :+1:

**Comment by silvioprog** [comment] 2018-11-17 13:31
Hello @Al-Muhandis . Reopening to make it as 'unsolved'. :-) Do you have any patch to fix it in the core?

**Comment by Al-Muhandis** [comment] 2018-11-17 13:51
> 
> 
> Hello @Al-Muhandis . Reopening to make it as 'unsolved'. :-) Do you have any patch to fix it in the core?

I added the callback unit above... 
If I could try, but I need to know what the line 599 in this [module ](https://github.com/silvioprog/brookframework/blob/v4.0.0/core/brookrouter.pas) is for?
```pascal
    if (APattern = US) and (APathInfo = ES) then
    begin
      ARedirect := True; // Why redirect? It causes an infinite loop
      Exit(True);
    end;
```

**Comment by silvioprog** [comment] 2018-11-17 14:02
The logic was rewritten by @uaply. The problem occurs using the broker [`brooktardigradebroker.pas`](https://github.com/silvioprog/brookframework/blob/v4.0.0/brokers/Tardigrade/brooktardigradebroker.pas)? If so, we can easily debug to solve it.

**Comment by Al-Muhandis** [comment] 2018-11-17 14:10
Hi @uaply ! Can you talk me a redirect is in this place for what?

**Comment by Al-Muhandis** [comment] 2018-11-17 14:15
> 
> 
> The problem occurs using the broker [`brooktardigradebroker.pas`](https://github.com/silvioprog/brookframework/blob/v4.0.0/brokers/Tardigrade/brooktardigradebroker.pas)? If so, we can easily debug to solve it.

No. I have not found anywhere how to use this broker. 

As I mentioned above one of my site works as a fast-cgi application using **BrookFCLFCGIBroker.pas**, I decided to try to convert it as a embedded server using **BrookFCLHttpDaemonBroker.pas** broker . The main problem was the endless redirects to the main page

**Comment by Al-Muhandis** [comment] 2018-11-17 14:52
> 
> 
> This is a smallest example showing how to use it: [demos/tardigrade](https://github.com/silvioprog/brookframework/tree/v4.0.0/demos/tardigrade).

I've already looked at him. The example is not explained to me the main. It shows that it just uses this broker. It works like an embedded server, right? That is, I can configure proxying via nginx from the selected port to listen on port 80 for a specific domain? 

By the way, this example requires the BrookTardigrade package, but there is no such package in this [folder](https://github.com/silvioprog/brookframework/tree/v4.0.0/packages)!

> 
> 
> Just for curiosity, what OS are you using?

Target: Debian, x86/64 (compile in Windows)

Sorry for asking but `brooktardigradebroker.pas` can be a good option for Apache/Nginx/(or any external HTTP server) replacement. This broker allows you to embed a high-performance HTTP server into your application using a minimal external cross-platform GNU library.

I'll try to figure it out again. What steps do I need to take to move the project from using `BrookFCLHttpDaemonBroker` to using `brooktardigradebroker`? Do I need to install something on Linux webserver? Some kind of library _.so_? Binding functionality for the application as a daemon, I will have to do it myself? 
P.S. I apologize for the abundance of questions. But I did not find any clear documentation for the new Tardigrade mechanism

**Comment by silvioprog** [comment] 2018-11-17 15:11
I have an idea and I would like to check if you agree. It seems the best way to sane all doubts is writing some 'step-by-step' document and share it as wiki page here. I'm going to enable the wiki option for this repository. Could you help me to write it? My OS is a Xubuntu 18.04, but I would like to check this broker on Debian too. If you agree, we can write the document (containing all steps) using Xubuntu/Debian as reference. What do you think?

**Comment by Al-Muhandis** [comment] 2018-11-17 15:33
What kind of help do you need? In principle, I can help however. The problem is, I just don't know what to write. )

**Comment by silvioprog** [comment] 2018-11-17 15:58
> I just don't know what to write

Don't worry, I'll like to do this part, starting for Ubuntu. :-)

Basically, we need:

1. a fresh Ubuntu/Debian installation; (I have a fresh one in a virtual machine)
2. latest stable Lazarus/FPC version;
3. download, build, install latest (stable) Sagui library;
4. download, build, install latest (beta) Brook Tardigrade;
5. download, build, install (stable) Brook 4.0.0.

I'll send all steps (commands) from 1 to 4 for you. I'm not familiar with Debian, but I think you could help me adapting the Ubuntu commands to Debian (maybe small changes, since Ubuntu is Debian based).

**Comment by silvioprog** [comment] 2018-11-17 22:34
I sent the 'step-by-step' page for Windows [here](https://github.com/silvioprog/brookframework/wiki) and it can be used as base to write the Ubuntu/Debian ones. :-)

**Comment by Al-Muhandis** [comment] 2018-11-19 11:15
> 
> 
> I sent the 'step-by-step' page for Windows [here](https://github.com/silvioprog/brookframework/wiki) and it can be used as base to write the Ubuntu/Debian ones. :-)

I'll take a look, though I don't seem to need to do separate pages for each OS. IMHO would suffice subsections

**Comment by Al-Muhandis** [comment] 2018-11-19 18:40
So, since we are already very much distracted from the subject of the issue, I create a new more relevant [issue ](https://github.com/silvioprog/brookframework/issues/160#issue-382343611)

**Comment by silvioprog** [comment] 2018-11-20 16:42
Indeed. Thanks for creating a new issue. I'll reply all questions there ... (this week I'll fix this issue #129)

**Comment by Al-Muhandis** [comment] 2018-11-22 22:36
> 
> 
> The logic was rewritten by @uaply. The problem occurs using the broker [`brooktardigradebroker.pas`](https://github.com/silvioprog/brookframework/blob/v4.0.0/brokers/Tardigrade/brooktardigradebroker.pas)? If so, we can easily debug to solve it.

So, I tested with `brooktardigradebroker` in Windows 10 and Debian: With this broker, the error does not occur. I mean of cause without using this [hack](https://github.com/silvioprog/brookframework/issues/129#issuecomment-439616934). Notice that It has not occured with FastCGi broker - only the broker for HTTP server (without tardigrade)

**Comment by silvioprog** [comment] 2018-11-23 20:42
@Al-Muhandis I have a fresh Ubuntu 18.10 copy (installed yesterday) in a virtual machine, and I can install the same web server (Apache?) you are using to check this bug. Could you share a minimal configuration of your server to reproduce the problem?

**Comment by Al-Muhandis** [comment] 2018-11-23 22:11
> 
> 
> @Al-Muhandis I have a fresh Ubuntu 18.10 copy (installed yesterday) in a virtual machine, and I can install the same web server (Apache?) you are using to check this bug. Could you share a minimal configuration of your server to reproduce the problem?

No problem ) It's simply HTTp Server with '/' registered with TBrookAction on any OS
[demo.zip](https://github.com/silvioprog/brookframework/files/2611788/demo.zip)

**Comment by Al-Muhandis** [comment] 2018-11-23 22:14
P.S.
Apache at me was used only in the scheme of fast cgi. The embedded HTTP server either uses Nginx or no additional web service at all (on an additional port, for example).

**Comment by silvioprog** [comment] 2018-11-26 16:51
@Al-Muhandis , thanks for sharing the example to reproduce the problem. I'll try it as soon as a possible to fix the problem.

**Comment by silvioprog** [comment] 2018-12-01 16:19
Hi guys, the patch `0004-Avoid-empty-pathinfo-fix-issue-129-reported-by-leled.patch` [attached here](https://github.com/silvioprog/brookframework/releases/tag/v4.0.0) finally fix the problem. Closing but feel free to reopen if the problem persists. Thank you very much!

**Closed by silvioprog** 2018-12-01 16:19 UTC
Labels: bug
